### ISSUE TITLE
biniance future 

### ISSUE THREAD

**Issue by cleitondm** [51bitquant/binance_grid_trader#10]
future binance does not work

401 error

**Comment by 51bitquant** [comment]
You may encounter the network problem, you may need to set the proxy host and port to connect to the binance exchange  server.

**Comment by kuratkull** [comment]
@51bitquant 
Although I set the proxy and port connection, I get a 401 error. Can you help for a detailed explanation or installation?

**Comment by 51bitquant** [comment]
> future binance does not work
> 
> 401 error

check your network. The code absolutely work.
> ping fabi.binance.com then see whether the network works well.
