### ISSUE TITLE
Backtesting and profit trailing support

### ISSUE THREAD

**Issue by didikrm** [51bitquant/binance_grid_trader#11]
Hi 
Just discovered this piece of software. I was wondering if it is possible to do backtesting before deploying the bot and if it supports profit trailing.

**Comment by 51bitquant** [comment]
This software is not supporting backtesting, if you want to backtest your strategy, you can try howtrader project , the following link is : https://github.com/51bitquant/howtrader.

**Comment by 51bitquant** [comment]
> Hi
> Just discovered this piece of software. I was wondering if it is possible to do backtesting before deploying the bot and if it supports profit trailing.

This software is not supporting backtesting, if you want to backtest your strategy, you can try howtrader project , the following link is : https://github.com/51bitquant/howtrader.
