### ISSUE TITLE
Error 400 on binance_future

### ISSUE THREAD

**Issue by jdk-sal3** [51bitquant/binance_grid_trader#13]
没有买单，根据盘口下买单: None, 时间: 2021-05-25 05:40:20.990356
请求没有成功: 400, 继续尝试请求

**Comment by jdk-sal3** [comment]
Found solution... set the Position Mode to "One-way Mode". 
Won't work with "Hedge Mode"

**Comment by 51bitquant** [comment]
> Found solution... set the Position Mode to "One-way Mode".
> Won't work with "Hedge Mode"

Yes, you're right, pls remember to set your Future Position Mode to "one-way Mode".
