### ISSUE TITLE
Missing gatewayModule

### ISSUE THREAD

**Issue by sabbathin** [51bitquant/binance_grid_trader#15]
no gatewayModule error when trying to use the binance grid stuff. I couldn't find it anywhere either
![image](https://user-images.githubusercontent.com/77943606/121794027-cc2fb900-cbb9-11eb-81aa-8433e37f82bc.png)
 grid

**Comment by 51bitquant** [comment]
> no gatewayModule error when trying to use the binance grid stuff. I couldn't find it anywhere either
> ![image](https://user-images.githubusercontent.com/77943606/121794027-cc2fb900-cbb9-11eb-81aa-8433e37f82bc.png)
> grid

check out the codes in your local project folder, you will find it.

**Comment by sabbathin** [comment]
Thank you, just rename __init__ to gateway, no problem so far. I'm
translating It, by the way. I'll be bidding along with It tomorrow.
Thanks once again for the app.
