### ISSUE TITLE
Illegal characters found in parameter 'price'

### ISSUE THREAD

**Issue by idsilent** [51bitquant/binance_grid_trader#16]
{'code': -1100, 'msg': "Illegal characters found in parameter 'price'; legal range is '^([0-9]{1,20})(\\.[0-9]{1,20})?$'."} 400

**Comment by 51bitquant** [comment]
You may experience the price like 0.0001, then it will show 10e-4, you need to use the round method or round_to method to make it show normal not in a scientific way.

**Comment by 51bitquant** [comment]
> {'code': -1100, 'msg': "Illegal characters found in parameter 'price'; legal range is '^([0-9]{1,20})(\.[0-9]{1,20})?$'."} 400

hello, I did modify the code, you can download the newly codes, then run it again. pls check out the README.md file. If you do experience the error, pls feel free to issue me. Thanks any way.

**Comment by 51bitquant** [comment]
This bug have fixed.
