### ISSUE TITLE
Error Code -2011 Unknown Order Sent

### ISSUE THREAD

**Issue by singaporeandurian** [51bitquant/binance_grid_trader#17]
Hello I used the same config as the sample:

{
  "platform": "binance_spot",
  "symbol": "ETHUSDT",
  "gap_percent": 0.005,
  "quantity": 0.001,
  "max_orders": 1,
  "proxy_host": "",
  "proxy_port": 0
}

To test functionality, but I get message saying {'code': -2011, 'msg': 'Unknown order sent.'} 400.

**Comment by 51bitquant** [comment]
you send the order's notional is very small, for the eth price is around 3000, you bought 0.001 eth, the order value is only 3 USDT value, for spot market, you need to buy at least 10USDT value, for future market, you need to buy at least 5 USDT value.

> Hello I used the same config as the sample:
> 
> { "platform": "binance_spot", "symbol": "ETHUSDT", "gap_percent": 0.005, "quantity": 0.001, "max_orders": 1, "proxy_host": "", "proxy_port": 0 }
> 
> To test functionality, but I get message saying {'code': -2011, 'msg': 'Unknown order sent.'} 400.

you send the order's notional is very small, for the eth price is around 3000, you bought 0.001 eth, the order value is only 3 USDT value, for spot market, you need to buy at least 10USDT value, for future market, you need to buy at least 5 USDT value.

**Comment by singaporeandurian** [comment]
> you send the order's notional is very small, for the eth price is around 3000, you bought 0.001 eth, the order value is only 3 USDT value, for spot market, you need to buy at least 10USDT value, for future market, you need to buy at least 5 USDT value.
> 
> > Hello I used the same config as the sample:
> > { "platform": "binance_spot", "symbol": "ETHUSDT", "gap_percent": 0.005, "quantity": 0.001, "max_orders": 1, "proxy_host": "", "proxy_port": 0 }
> > To test functionality, but I get message saying {'code': -2011, 'msg': 'Unknown order sent.'} 400.
> 
> you send the order's notional is very small, for the eth price is around 3000, you bought 0.001 eth, the order value is only 3 USDT value, for spot market, you need to buy at least 10USDT value, for future market, you need to buy at least 5 USDT value.

I see... will I be able to adjust the bot to decrease minimum value for spot market from 10USDT to something like 1 USDT instead? Or is this a limitation of Binance? Thank you!

**Comment by singaporeandurian** [comment]
Just found out that Binance has a 10 USD spot minimum limit for orders.

**Comment by thearthouse** [comment]
hi , shibusdt the order_volume should be shib or usdt

**Comment by thearthouse** [comment]
> hi , shibusdt the order_volume should be shib or usdt

hi , shibusdt the order_volume should be shib or usdt

**Comment by 51bitquant** [comment]
> > hi , shibusdt the order_volume should be shib or usdt
> 
> hi , shibusdt the order_volume should be shib or usdt

the number of SHIB. order_volume means how many SHIB you want to place for the pair of SHIBUSDT.
