### ISSUE TITLE
spot_grid_strategy.py

### ISSUE THREAD

**Issue by dynahpointch** [51bitquant/binance_grid_trader#24]
Hi Great Work,
I have two questions about.

    36 # the strategy will stop when the price break the upper/bottom price, if you set the close_position when stop True,
    37 # it will automatically close your position.

Where can I find this config setting close_position ?
Is it true that the upper limit will be ignored and future buy's will be submitted ?

Kind Regards.

**Comment by 51bitquant** [comment]
great.
