### ISSUE TITLE
怎么没有最低价最高价？

### ISSUE THREAD

**Issue by happmaoo** [51bitquant/binance_grid_trader#6]
最低14000买入，最高20000卖出，区间套利怎么设置？

**Comment by 51bitquant** [comment]
这个你可以基于howtrader去写，链接：https://github.com/51bitquant/howtrader, 里面有关于网格策略的代码。你可以参考网易云课堂的课程， 课程链接：https://study.163.com/course/introduction/1210904816.htm。
