### ISSUE TITLE
error

### ISSUE THREAD

**Issue by cleitondm** [51bitquant/binance_grid_trader#7]
{
  "platform": "binance_spot",
  "symbol": "XLMETH",
  "api_key": "",
  "api_secret": "",
  "gap_percent": 0.01,
  "quantity": 1,
  "min_price": 0.01,
  "min_qty": 0.01,
  "max_orders": 1,
  "proxy_host": "",
  "proxy_port": 0
}

{'code': -1013, 'msg': 'Invalid price.'} 400
{'code': -1013, 'msg': 'Invalid price.'} 400
{'code': -1013, 'msg': 'Invalid price.'} 400
{'code': -1013, 'msg': 'Invalid price.'} 400
{'code': -1013, 'msg': 'Invalid price.'} 400
{'code': -1013, 'msg': 'Invalid price.'} 400
{'code': -1013, 'msg': 'Invalid price.'} 400
{'code': -1013, 'msg': 'Invalid price.'} 400
{'code': -1013, 'msg': 'Invalid price.'} 400
{'code': -1013, 'msg': 'Invalid price.'} 400

I always get lost in values

**Comment by cleitondm** [comment]
Trading Rules
Minimum amount of trade 1 XLM
Minimum price movement 0.00000001 ETH
Minimum order size 0.01 ETH

**Comment by cleitondm** [comment]
"platform": "binance_spot",
"symbol": "XLMETH",
"api_key": "",
"api_secret": "",
"gap_percent": 0.01,
**"quantity": 1,**
**"min_price": 0.01,**
**"min_qty": 0.00000001,**
"max_orders": 1,
"proxy_host": "",
"proxy_port": 0
}

**Comment by 51bitquant** [comment]
you can config like the follow:

```
{"platform": "binance_spot",
"symbol": "XLMETH",
"api_key": "",
"api_secret": "",
"gap_percent": 0.01,
"quantity": 100,
"min_price": 0.00000001,
"min_qty": 1,
"max_orders": 1,
"proxy_host": "",
"proxy_port": 0
}

```

remember in binance, the min_qty is the minimum amount you trade, for the XLMETH paris, the minimum quantity is 1 XLM,  the min_qty is 0.00000001, the quantity is the amount you want to trade each time, but at least, you should trade amount's value over 10 USDT each time.

OK, I will upload a video describe how to use the project in youtube asap.
